version: '3'

services:

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - ./frontend/:/app/build/

  nginx:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    network_mode: host
    depends_on:
      - frontend

volumes:
  static:
  media:
