# Generated by Django 3.2.3 on 2023-12-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='cooking_time',
        ),
    ]
