# Generated by Django 3.2.3 on 2023-12-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_work_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цветовой HEX-код'),
        ),
    ]
