# Generated by Django 3.2.3 on 2024-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='works/videos/', verbose_name='Видео'),
        ),
    ]
