# Generated by Django 3.2.3 on 2024-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works/images/', verbose_name='Картинка'),
        ),
    ]
