# Generated by Django 3.2.3 on 2024-01-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_work_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='materials',
        ),
    ]
